<?php

namespace app\modules\ui\generator;

use yii\gii\Generator;
use yii\helpers\Html;
use yii\base\InvalidArgumentException;
use yii\base\RuntimeException;

class FrontendGenerator extends Generator
{
    public $viewName = 'hello-world';   // Name of the view file to be generated
    public $templateName = 'default';    // Name of the template to use
    public $projectPath; // Path for custom project location

    public $title = 'Hello World';

    // Define templates property
    public $templates = [
        'default' => '@app/modules/ui/generator/templates/default', // Define default template path
    ];

    public function getName()
    {
        return 'Frontend Hello World Generator';
    }

    public function getDescription()
    {
        return 'This generator creates a simple Hello World view with customizable templates.';
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            ['viewName', 'filter', 'filter' => 'trim'],
            ['viewName', 'required'],
            ['viewName', 'match', 'pattern' => '/^\w+(?:-\w+)*$/', 'message' => 'Only word characters and dashes are allowed.'],
            ['templateName', 'string'], // Rule for the template name
            ['projectPath', 'string'], // Rule for the project path
        ]);
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'viewName' => 'View Name',
            'templateName' => 'Template Name', // Label for the new attribute
            'projectPath' => 'Path of Project', // Label for project path
        ]);
    }

    public function hints()
    {
        return array_merge(parent::hints(), [
            'viewName' => 'Enter the name of the view file (without .php) to be generated. Only word characters and dashes are allowed.',
            'templateName' => 'Select the template to be used for generating the view.',
            'projectPath' => 'Specify the custom path where you want the generated file to be saved.',
        ]);
    }

    public function generate()
    {
        $files = [];
        $viewPath = $this->projectPath ? \Yii::getAlias($this->projectPath) : \Yii::$app->getViewPath(); // Get custom or default view path

        // Ensure the view path is writable
        if (!is_writable($viewPath)) {
            throw new InvalidArgumentException("View path is not writable: {$viewPath}");
        }

        // Define the content for the view file as inline HTML
        $renderedContent = <<<HTML
<?php
use yii\helpers\Html;

/* @var \$this yii\web\View */

?>

<div class="hello-world">
    <h1>Hello Hmida!</h1>
    <p>This is a simple Hello World view generated by the Yii2 generator.</p>
</div>
HTML;

        // Create the new view file
        $codeFile = new \yii\gii\CodeFile(
            $viewPath . '/' . $this->viewName . '.php',
            $renderedContent // Use the inline HTML content for the new view file
        );

        // Save the file and check for errors
        if (!$codeFile->save()) {
            throw new RuntimeException("Failed to save the generated file: {$codeFile->path}");
        }

        $files[] = $codeFile; // Add to the list of generated files
        return $files; // Return the generated files
    }

    public function getTemplatePath()
    {
        // Construct the path to the template using DIRECTORY_SEPARATOR for compatibility
        return \Yii::getAlias('@app/modules/ui/generator/templates/' . $this->templateName . '/view.php');
    }
}
