<?php
echo "<?php\n";
?>

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Hello World';
?>
<div class="hello-world">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Hello, World! This is a simple view generated by the Frontend Generator using <?= $framework ?>.</p>
</div>